```plantuml
@startwbs
skinparam backgroundColor Snow

* ISAC BookShelf

** Учет книг для пользователей
*** Каталог книг
**** Список всех зарегистрированных книг с фильтрацией
**** Быстрый поиск книги по названию или ISBN
**** Детальная информация о книге
**** Просмотр оценок книги менторами
**** Список избранных книг
**** Добавление книги в Избранное
*** Добавление неучтенных книг
**** Оформление заявки на регистрацию книги по ссылке на Amazon.com
**** Автозаполнение полей информаци о книге на основании ссылки на amazon.com
**** Ручная валидация заявок на регистрацию книги администратором
**** Список заявок на регистрацию книги для валидации администратором
**** Автоматическая валидация заявок на регистрацию книги
*** Формирование заявки на оценку книги
**** Заявка на оценку книги с указаниям одного или нескольких потенциального оценщиков из списка менторов
**** Просмотр статуса заявки на оценку книги
*** Просмотр списков для чтения
**** Доступ ко всем спискам для чтения с фильтрами
**** Просмотр списков для чтения ментора
**** Детальная информация списка для чтения

** Учет рекомендаций менторами
*** Оценка книги
**** Оценка книги ментором
**** Рецензия на книгу ментором
**** Отказ от оценки книги
**** Оценка книги с Книжной полки
**** Переадресация оценки
*** Учет списков рекомендаций
*** Учет заявок на оценку книг
**** Просмотр персональных зявок на оценку книги
**** Переадресация заявок на оценку книги на другого ментора

** Аренда книг из библиотеки клуба пользователями
*** Заявка на чтение книги
*** Учет персональных заявок на чтение
*** Учет персональных трансферов
*** Пролонгация аренды книги

** Администрирование аренды книг библиотеки клуба администраторами клуба
*** Получение списка книг к покупке
*** Учет состояние закупок
*** Учет книг библиотеки
*** Учет трансферов арендованных книг
*** Списание книг
*** Учет пролонгаций аренды книг

** "Удобная логистика"
*** Трансфер книг на офлайновых встречах клуба
*** Трансфер книг с помощью сторонних почтовых сервисов
*** Объединение получений и возвратов книг в пакеты для обработки администратором
**** Список книг для трансфера через почту
**** Список книг для трансфера на офлайн встрече
*** Интеграция с сторонними почтовыми сервисами
**** Автоматическое формирование почтовых накладных
**** Синхронизация состояния посылки со статусом аренды
**** Обновление граничной даты хранения книги на отделении почтового сервиса


@endwbs
```