```plantuml
@startwbs
skinparam backgroundColor Snow
<style>
wbsDiagram {
 .mvp * {
     BackgroundColor Blue
     FontColor White
 }
 .v1 * {
     BackgroundColor DeepSkyBlue
     FontColor Black
 }
 .v2 * {
     BackgroundColor PowderBlue
     FontColor Black
 }
}
</style>

legend
|= Color |= Type |
|<#Blue>| MVP |
|<#DeepSkyBlue>| v1 release |
|<#PowderBlue>| v2 release |
end legend

* ISAC BookShelf

** Учет книг для пользователей <<mvp>>
*** Каталог книг
**** Список всех зарегистрированных книг с фильтрацией
**** Быстрый поиск книги по названию или ISBN
**** Детальная информация о книге
**** Просмотр оценок книги менторами
**** Список избранных книг
**** Добавление книги в Избранное
*** Добавление неучтенных книг
**** Оформление заявки на регистрацию книги по ссылке на Amazon.com
**** Автозаполнение полей информаци о книге на основании ссылки на amazon.com
**** Ручная валидация заявок на регистрацию книги администратором
**** Список заявок на регистрацию книги для валидации администратором
**** Автоматическая валидация заявок на регистрацию книги <<v2>>
**** Регистрация книги администратором
*** Формирование заявки на оценку книги
**** Заявка на оценку книги с указаниям одного или нескольких потенциального оценщиков из списка менторов
**** Просмотр статуса заявки на оценку книги
*** Просмотр списков для чтения
**** Доступ ко всем спискам для чтения с фильтрами
**** Просмотр списков для чтения ментора <<v2>>
**** Детальная информация списка для чтения

** Учет рекомендаций менторами <<mvp>>
*** Оценка книги
**** Оценка книги ментором
**** Рецензия на книгу ментором
**** Отказ от оценки книги
**** Оценка книги с Книжной полки
**** Переадресация оценки
*** Учет списков для чтения ментора
**** Управление списками для чтения ментора
**** Описание для книги в списке для чтения
*** Учет заявок на оценку книг
**** Просмотр персональных зявок на оценку книги
**** Переадресация заявок на оценку книги на другого ментора
**** Отказ от оценки книги

** Аренда книг из библиотеки клуба пользователями <<v1>>
*** Заявка на аренду книги
*** Учет персональных заявок на аренду
*** Учет персональных трансферов
*** Пролонгация аренды книги

** Администрирование аренды книг библиотеки клуба администраторами клуба  <<v1>>
*** Получение списка книг к покупке
*** Учет состояние закупок
*** Учет книг библиотеки
*** Учет трансферов арендованных книг
*** Списание книг
*** Учет пролонгаций аренды книг

** "Удобная логистика"  <<v1>>
*** Трансфер книг на офлайновых встречах клуба
*** Трансфер книг с помощью сторонних почтовых сервисов
*** Объединение получений и возвратов книг в пакеты для обработки администратором
**** Список книг для трансфера через почту
**** Список книг для трансфера на офлайн встрече
*** Интеграция с сторонними почтовыми сервисами <<v2>>
**** Автоматическое формирование почтовых накладных
**** Синхронизация состояния посылки со статусом аренды 
**** Обновление граничной даты хранения книги на отделении почтового сервиса


@endwbs
```